### ISSUE TITLE
It does not work anymore

### ISSUE THREAD

**Issue by tavibe** [zyphos/belgium-replay-tv#10]
Dear all,

Thank you for this great kodi plugin.
Unfortunately today the RTBF stopped working. When I enter in the RTBF folder I used to see all the shows listed in alphabetical order, now see only one folder "Directs".

It would be great if you could look into it and possibly fix it. I hope it's not something major.

Thank you very much

**Comment by zyphos** [comment]
I noticed that too. I will try to fix it tonight.

**Comment by mauriceriguel** [comment]
thank you!

**Comment by thbjacobs** [comment]
Hi,

I have made a fix (tested working on Kodi 16) and a pull request, I'm new to Github so I'm not sure I did it properly

**Comment by zyphos** [comment]
Working perfectly. I merged it. Thank you!

**Comment by tavibe** [comment]
You are amazing
Thank you Zyphos and Maurice
My kids are your number one fans, you made them very happy!

**Comment by mauriceriguel** [comment]
all credits belong to zyphos! i'm just an end user like your kids ;-)
thank you very much for your efforts zyphos!

**Comment by zyphos** [comment]
The fix comes from thbjacobs. Credits go to him.
