### ISSUE TITLE
contenu auvio non disponible

### ISSUE THREAD

**Issue by Wanegain** [zyphos/belgium-replay-tv#14]
Bonjour,

Dans le replay RTBF je ne vois que les flux en live mais je n'ai plus rien comme contenu, est-ce normal ?
C'est quand même bien pratique tous les dessins animés pour les enfants :)

Merci beaucoup pour l'addon au passage 👍 

Je suis sur un rpi2 avec libreelec

EDIT : je viens de voir à l'instant qu'il y avait une nouvelle version qui apparemment corrige ça... Désolé pour le post je vais vérifier ça !

**Comment by Wanegain** [comment]
Malgré la mise à jour je n'ai aucun contenu à part les directs... :(

**Comment by tavibe** [comment]
Je confirme, moi non-plus je ne vois plus l'autre contenu

**Comment by zyphos** [comment]
En effet, dès que j'ai 5 min je regarde ce qu'il se passe.

**Comment by zyphos** [comment]
C'est corrigé:
https://github.com/zyphos/belgium-replay-tv/releases/tag/0.0.27

**Comment by Wanegain** [comment]
Excellent je teste ça ce soir :+1: 
Encore merci pour la réactivité et le plugin ! Manque plus qu'un repo pour mettre à jour automatiquement l'appli et c'est parfait :smiley:

**Comment by tavibe** [comment]
Un grand merci
Ca fonctionne bien

**Comment by Wanegain** [comment]
Je confirme ! Merci beaucoup 🥇
