### ISSUE TITLE
RTBF not available anymore

### ISSUE THREAD

**Issue by tavibe** [zyphos/belgium-replay-tv#19]
Hi,
A few days ago RTBF stopped working :(
I checked in the logs and I see something like this:
`23:24:23 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_7-a-la-une%3Fid%3D2250373&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_7-a-la-une%3Fid%3D2250373&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_7-a-la-une%3Fid%3D2227956&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_7-a-la-une%3Fid%3D2227956&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1858996896 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_7-a-la-une%3Fid%3D2225574&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1858996896   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_7-a-la-une%3Fid%3D2225574&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_gilles-le-suisse-fait-la-descente-de-la-lesse%3Fid%3D2258065&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_gilles-le-suisse-fait-la-descente-de-la-lesse%3Fid%3D2258065&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_mathieu-amalric%3Fid%3D2258064&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_mathieu-amalric%3Fid%3D2258064&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1858996896 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_la-detchosphere%3Fid%3D2258063&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1858996896   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_la-detchosphere%3Fid%3D2258063&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_soigner-a-tout-prix%3Fid%3D2258062&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_soigner-a-tout-prix%3Fid%3D2258062&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1858996896 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_a-l-ombre-du-samusocial%3Fid%3D2258060&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1858996896   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_a-l-ombre-du-samusocial%3Fid%3D2258060&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_le-pol-dance-la-grande-assemblee-de-l-onu%3Fid%3D2258059&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_le-pol-dance-la-grande-assemblee-de-l-onu%3Fid%3D2258059&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_gilles-le-suisse-a-walibi-avec-le-mr%3Fid%3D2255446&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_gilles-le-suisse-a-walibi-avec-le-mr%3Fid%3D2255446&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_la-detchosphere%3Fid%3D2255440&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:23 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_la-detchosphere%3Fid%3D2255440&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:26 T:1907058008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: '\xef'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.belgium/addon.py", line 78, in <module>
                                                sys.modules[channel_module_name].Channel(context)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.belgium/channel.py", line 188, in __init__
                                                History().update(context)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.belgium/channel.py", line 132, in update
                                                categories = self._read()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.belgium/channel.py", line 161, in _read
                                                categories = pickle.load(f)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/pickle.py", line 1370, in load
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/pickle.py", line 858, in load
                                            KeyError: '\xef'
                                            -->End of Python script error report<--
23:24:26 T:1789404016   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_7-a-la-une%3Fid%3D2252895&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une]
23:24:56 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_magazine-info-samedi-7-a-la-une%3Fid%3D2260622&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:56 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_magazine-info-samedi-7-a-la-une%3Fid%3D2260622&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:56 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_la-detchosphere%3Fid%3D2255440&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:56 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_la-detchosphere%3Fid%3D2255440&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:56 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_gilles-le-suisse-a-walibi-avec-le-mr%3Fid%3D2255446&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:56 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_gilles-le-suisse-a-walibi-avec-le-mr%3Fid%3D2255446&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:56 T:1846926224 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_le-pol-dance-la-grande-assemblee-de-l-onu%3Fid%3D2258059&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:56 T:1846926224   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_le-pol-dance-la-grande-assemblee-de-l-onu%3Fid%3D2258059&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:56 T:1848327160 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(plugin) in plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_a-l-ombre-du-samusocial%3Fid%3D2258060&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
23:24:56 T:1848327160   ERROR: InputStream: Error opening, plugin://plugin.video.belgium/?url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Fdetail_a-l-ombre-du-samusocial%3Fid%3D2258060&channel_id=rtbf&category_url=https%3A%2F%2Fwww.rtbf.be%2Fauvio%2Femissions%2Fdetail_7-a-la-une%3Fid%3D8574&action=play_video&category_id=8574&category_name=7+%C3%A0+la+Une
`

Unfortunatelly I do not know python and I have no idea how to debug it. 
I tried to access from my minix box the rtbf via the chrome browser and it's working fine, it's just the xbmc plugin...

It would be great if somebody could fix it!

Many thanks

**Comment by tavibe** [comment]
I have updated the above error

**Comment by zyphos** [comment]
Have you tried another working video plug-in ? If yes could you tell ? I will check a method that is working.
Because the error is not a python error, it is a C or C++ error in the Curl library. But CURL should not handle URI that begin with "plugin://".
