### ISSUE TITLE
Tv Com ne fonctionne plus

### ISSUE THREAD

**Issue by Joreel** [zyphos/belgium-replay-tv#24]
Seul Bx1 semble encore fonctionner. La RTBF et Tv Com ne fonctionnent plus.

**Comment by zyphos** [comment]
J'ai corrigé Tv Com, par contre RTBF fonctionne bien ici.

**Comment by Joreel** [comment]
Merci! J'examinerai le problème avec la RTBF. Je pense qu'on peut fermer le "issue" entre temps.
