### ISSUE TITLE
Bug playing RTBF videos

### ISSUE THREAD

**Issue by ze-big-ant** [zyphos/belgium-replay-tv#25]
Hi, 
I can't play Auvio's videos anymore. The list of JTs is up-to-date but when I try to launch a video (JT of 19h30 for instance), I got this log message:

[kodi.log](https://github.com/zyphos/belgium-replay-tv/files/3005331/kodi.log)

The url might have changed on Auvio website... Could you check what's the matter, please?
Thank you in advance.
Anthony

**Comment by zyphos** [comment]
I was already working on this 10 min ago.
It is fixed in release 0.0.32.

**Comment by ze-big-ant** [comment]
Wow, thanks!

Could you explain what you did? I'm a computer engineer and I'm interested in this plugin and how it works.

Cheers. And many thanks for this plugin. We use it all the time.

**Comment by ze-big-ant** [comment]
Sorry but your release 0.0.32 doesn't work. But it seems the problem is different:

[kodi.log](https://github.com/zyphos/belgium-replay-tv/files/3008921/kodi.log)
