### ISSUE TITLE
RTBF/auvio not available anymore :-(

### ISSUE THREAD

**Issue by dur3x** [zyphos/belgium-replay-tv#6]
Hello, it looks that the new live video from RTBF: auvio is not working anymore.
Can you help me please ? I already try to investigate a little bit but it looks more complicated than I think :-(
Thanks in advance !

**Comment by zyphos** [comment]
Indeed I noticed that 2 days ago. But I need to apologize, I don't have time to fix it now.

**Comment by Wilcobxl** [comment]
D'après ce que j'ai constaté, on dirait un problème d'interprétation de path relatifs dans les fichiers m3u8.
un exemple : 

Le parsing s'effectue correctement ( sur la version contenue dans  mon dernier pull request) jusqu'à récupérer l'adresse http://rtbf.l3.freecaster.net/live/rtbf/geo/open/abb1916b08d3b03ffd00218d3d48deda80aa3898/purevision.m3u8?token=04fe5b90b1d52355f235d. le fichier contient plusieurs paths relatifs vers differents m3u8, correspondants au flux de différentes qualités.
Le plugin sélectionne correctement un des fichiers : http://rtbf.l3.freecaster.net/live/rtbf/geo/open/abb1916b08d3b03ffd00218d3d48deda80aa3898/../../open/3e4edc0e2eb0fa293559e6b83d037273e335a053/purevision-audio_1=128000-video=2000000.m3u8  (= http://rtbf.l3.freecaster.net/live/rtbf/geo/open/3e4edc0e2eb0fa293559e6b83d037273e335a053/purevision-audio_1=128000-video=2000000.m3u8 , et en lit le contenu, qui est composé de paths relatifs vers les différents fichiers .ts ( par exemple: ../../../be/95078169b1050ea601a50598eed983dd092bb29a/events(2)/laune-audio_1=128000-video=2000000-184232412.ts) . 
Là, le plugin crache une erreur 400 pour les chemins vers les ts. On dirait qu'il y a un problème d'interprétation des multiples paths relatifs: le plugin tente de télécharger : 
http://rtbf.l3.freecaster.net/live/rtbf/geo/open/abb1916b08d3b03ffd00218d3d48deda80aa3898/../../../../../../be/b16f6d05a76b6f52525cdb4a9922f1befba5fc3c/3e4edc0e2eb0fa293559e6b83d037273e335a053/open/../../purevision-audio_1=128000-video=2000000-368611467.ts

Voilà où j'en suis. Je n'ai moi-même que très peu de temps, et je n'ai pour l'instant pas encore trouvé où exactement se trouve le problème et comment le résoudre. J'espere que ce blabla sera utile....

**Comment by dur3x** [comment]
Merci Wilcobxl, grâce à tes explications j'ai pu un peu creusé ce qui se produisait...
Pour moi c'est comme t'as dit, il y a un soucis avec la lecture des chemins relatifs, et plus exactement le premier fichier donné en entrée à la fonction channel.playUrl. Il semblerait que celle-ci nécessite un path absolu pour commencer. Pour faire fasse à cela, j'ai fixé comme ceci sur base de ton dernier pull:

```
        if hls_stream_url is not None:
            print "HLS stream"
            stream_url = hls_stream_url.group(1).replace("\\", "")
            print ">>> " + stream_url
            data = channel.get_url(stream_url)
            best_resolution_path = data.split("\n")[-2]
            hls_stream_url = stream_url[:stream_url.rfind('open')] + best_resolution_path[5:]
            print "HLS stream url: >" + hls_stream_url + "<"
            channel.playUrl(hls_stream_url)
```

Pour l'instant cela semble fonctionner à merveille excepté qu'il fasse de temps en temps cliquer 2-3 fois sur le lien dans kodi pour que la vidéo démarre mais une fois démarrée c'est bon.

ps: pour finir ton commentaire aura été utile 👍
